---
name: Application CI-CD

on:

  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
    build:
      runs-on: self-hosted
      steps:
      
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Dependencies
          run: |
            pip install pytest

        - name: Run Tests
          run: |
            pytest

        - name: Build Dashboard Image
          run: |
            docker build -t can-dashboard:${{ env.BUILD_NUMBER }} ./dashboard

        - name: Build Parser Image
          run: |
            docker build -t can-parser:${{ env.BUILD_NUMBER }} ./parser

        - name: Build Simulator Image
          run: |
            docker build -t vehicle-simulator:${{ env.BUILD_NUMBER }} ./simulator

        - name: Load Images
          run: |
            minikube image load can-dashboard:${{ env.BUILD_NUMBER }}
            minikube image load can-parser:${{ env.BUILD_NUMBER }}
            minikube image load vehicle-simulator:${{ env.BUILD_NUMBER }}

        - name: Verify Images
          run: |
            minikube image ls | grep can-dashboard
            minikube image ls | grep can-parser
            minikube image ls | grep vehicle-simulator
    
    deploy-dev:
      needs: build
      runs-on: self-hosted
      environment : dev
      steps:
        - name: Update DEV Tags
          run: |
            cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops-helm

            git pull origin master

            git remote set-url origin \
            https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops-helm.git

            echo "Updating manifests for build ${env.BUILD_NUMBER}"

            # Dashboard
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/dashboard/values-dev.yaml

            # Parser
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/parser/values-dev.yaml

            # Vehicle Simulator
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/vehicle-simulator/values-dev.yaml

            git config user.name "can-platform-ci"
            git config user.email "can-platform-ci@local"
            git status
            git add .  
            git commit -m "Promote build ${env.BUILD_NUMBER} to DEV" || true
            git push origin master
  
    deploy-qa:
      needs : deploy-dev
      runs-on: self-hosted
      environment : qa
      steps:
        - name: Update QA Tags
          run: |
            cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops-helm
            git pull origin master
            git remote set-url origin \
            https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops-helm.git

            echo "Updating manifests for build ${env.BUILD_NUMBER}"

            # Dashboard
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/dashboard/values-qa.yaml

            # Parser
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/parser/values-qa.yaml

            # Vehicle Simulator
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/vehicle-simulator/values-qa.yaml

            git config user.name "can-platform-ci"
            git config user.email "can-platform-ci@local"
            git status
            git add .  
            git commit -m "Promote build ${env.BUILD_NUMBER} to QA" || true
            git push origin master
  
    deploy-prod:
      needs : deploy-qa
      runs-on: self-hosted
      environment : prod
      steps:
        - name: Update PROD Tags
          run: |
            cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops-helm
            git pull origin master
            git remote set-url origin \
            https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops-helm.git

            echo "Updating manifests for build ${env.BUILD_NUMBER}"

            # Dashboard
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/dashboard/values-prod.yaml

            # Parser
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/parser/values-prod.yaml

            # Vehicle Simulator
            sed -i "s|tag: \".*\"|tag: \"${env.BUILD_NUMBER}\"|" \
            applications/vehicle-simulator/values-prod.yaml

            git config user.name "can-platform-ci"
            git config user.email "can-platform-ci@local"
            git status
            git add .  
            git commit -m "Promote build ${env.BUILD_NUMBER} to PROD" || true
            git push origin master


