---
name: Application CI-CD

on:

  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:

  application:

    runs-on: self-hosted

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pytest

      - name: Run Tests
        run: |
          pytest

      - name: Build Dashboard Image
        run: |
          docker build -t can-dashboard:${{ env.BUILD_NUMBER }} ./dashboard

      - name: Build Parser Image
        run: |
          docker build -t can-parser:${{ env.BUILD_NUMBER }} ./parser

      - name: Build Simulator Image
        run: |
          docker build -t vehicle_data_simulator:${{ env.BUILD_NUMBER }} ./simulator

      - name: Load Images
        run: |
          minikube image load can-dashboard:${{ env.BUILD_NUMBER }}
          minikube image load can-parser:${{ env.BUILD_NUMBER }}
          minikube image load vehicle_data_simulator:${{ env.BUILD_NUMBER }}

      - name: Configure Git Remote
        run: |
          cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops

          git remote set-url origin \
          https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops.git

          echo "Updating manifests for build ${BUILD_NUMBER}"

          # Dashboard
          sed -i \
          "s|can-dashboard:[0-9]*|can-dashboard:${BUILD_NUMBER}|g" \
          dashboard/dashboard_deployment.yaml

          # Parser
          sed -i \
          "s|can-parser:[0-9]*|can-parser:${BUILD_NUMBER}|g" \
          parser/parser_deployment.yaml

          # Simulator
          sed -i \
          "s|vehicle_data_simulator:[0-9]*|vehicle_data_simulator:${BUILD_NUMBER}|g" \
          simulator/vehicle_simulator_deployment.yaml

          git config user.name "can-platform-ci"
          git config user.email "can-platform-ci@local"

          git add .
    
          echo "Dashboard:"
          grep image dashboard/dashboard_deployment.yaml

          echo "Parser:"
          grep image parser/parser_deployment.yaml

          echo "Simulator:"
          grep image simulator/vehicle_simulator_deployment.yaml
`

          git commit -m "Update application images to build ${BUILD_NUMBER}" || true

          git push origin master
      - name: Verify Images
        run: |
          minikube image ls | grep can-dashboard
          minikube image ls | grep can-parser
          minikube image ls | grep vehicle_data_simulator
