name: Rollback-Release

on:
  workflow_dispatch:
    inputs:
      rollback_release_number:
        description: "Release number to restore, for example 27"
        required: true
        type: string

jobs:
  rollback:
    name: Rollback production
    runs-on: self-hosted

    steps:
      - name: Rollback prod Environment 
        run: |
          cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops-helm

          git remote set-url origin \
          https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops-helm.git

          git pull origin master

          echo "Updating manifests for build ${{ inputs.rollback_release_number }}"

          RELEASE_NUMBER="${{ inputs.rollback_release_number }}"
          RELEASE_FILE="releases/${RELEASE_NUMBER}.yaml"

          # Extract component-specific tags
          DASHBOARD_TAG=$(grep -A1 "^dashboard:" "${RELEASE_FILE}" | grep "tag:" | awk -F'"' '{print $2}')
          PARSER_TAG=$(grep -A1 "^parser:" "${RELEASE_FILE}" | grep "tag:" | awk -F'"' '{print $2}')
          SIMULATOR_TAG=$(grep -A1 "^simulator:" "${RELEASE_FILE}" | grep "tag:" | awk -F'"' '{print $2}')

          echo "Dashboard tag : ${DASHBOARD_TAG}"
          echo "Parser tag    : ${PARSER_TAG}"
          echo "Simulator tag : ${SIMULATOR_TAG}"

          # Dashboard
          sed -i "s|tag: \".*\"|tag: \"${DASHBOARD_TAG}\"|" \
          applications/dashboard/values-prod.yaml

          # parser
          sed -i "s|tag: \".*\"|tag: \"${PARSER_TAG}\"|" \
          applications/parser/values-prod.yaml

          # simulator
          sed -i "s|tag: \".*\"|tag: \"${SIMULATOR_TAG}\"|" \
          applications/vehicle-simulator/values-prod.yaml
        
          git config user.name "can-platform-ci"
          git config user.email "can-platform-ci@local"
          git status
          git add \
          applications/dashboard/values-prod.yaml \
          applications/parser/values-prod.yaml \
          applications/vehicle-simulator/values-prod.yaml
          git commit -m "Rollback PROD to release ${{ inputs.rollback_release_number }}" || true
          git push origin master
