name: Rollback
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

      rollback_tag:
        description: "Docker Tag"
        required: true

jobs:

  rollback:

    runs-on: self-hosted

    steps:
      - name: Rollback prod Environment 
        run: |
          cd /home/reenajadhav/canlog-dashboard-live/can-platform-gitops-helm

          git pull origin master

          git remote set-url origin \
          https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/reenajadhav/can-platform-gitops-helm.git

          echo "Updating manifests for build ${input.rollback_tag}"

          # Dashboard
          sed -i "s|tag: \".*\"|tag: \"${input.rollback_tag}\"|" \
          applications/dashboard/values-dev.yaml

          git config user.name "can-platform-ci"
          git config user.email "can-platform-ci@local"
          git status
          git add .  
          git commit -m "Promote build ${input.rollback_tag} to DEV" || true
          git push origin master
  