--- 
name: security-scan
on:

  push:
    branches:
      - main
jobs:

  platform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check for hardcoded secrets
        run: |
          if grep -R -i \
            --exclude-dir=.git \
            --exclude="*.md" \
            --exclude=".github/workflows/*" \
            -E 'password=|secret=|token=|apikey=' .; then
            echo "Potential secret found"
            exit 1
          fi
