--- 
name: security-scan
on:

  push:
    branches:
      - main
jobs:

  platform:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check for passwords
        run: |
          grep -R "password" . && exit 1 || true
